### ISSUE TITLE
Add FXGL tutorial link to contribution guidelines file

### ISSUE THREAD

**Issue by dylan-power** [jvondermarck/dinosaur-exploder#10]
**Is your feature request related to a problem? Please describe.**
This is not related to a current problem but will improve documentation.

**Describe the solution you'd like**
Add [this video link](https://www.youtube.com/watch?v=48rVgdq0mFA) to our [contribution guidelines file](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md). This should be added just before the 'Types of Contributions Accepted' section. A short descriptive sentence should be written for context e.g. "If you haven't developed using JavaFX and FXGL, please watch this video first."

**Comment by jdcreedon** [comment]
@dylan-power I'll take this one, can you assign it to me please?

**Comment by Tomiiwa** [comment]
Hi, I want to work on this, if it is still available

**Comment by jvondermarck** [comment]
@filegrunt Hi, are you still working on it? 😊
