### ISSUE TITLE
[Bug]: impossible to turn the music back on

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#106]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate bugs.

### ❌ Current Behavior

When I click on the green button it does not turn off the audio.
![image](https://github.com/dylan-power/dinosaur-exploder/assets/62793491/93f12fd2-c36e-409c-b89e-3441fe780074)

### ✅ Expected Behavior

When I click on the button, the music needs to play again after I turned it off.

### 🚩 Steps To Reproduce

1. Open the game
2. Turn off the sound on the top right green button
3. Try to turn on the music again

### 💻 Environment

```markdown
- OS: Windows 11
- Game version: 1.0.2
```

**Comment by adisin17** [comment]
Hi @jvondermarck , I am new here and would like to take this up

**Comment by jvondermarck** [comment]
@adisin17 Hi there !! Let's go, this issue is all yours ! 😊

**Comment by Thompson6626** [comment]
Hi @jvondermarck , I'm also new and would like to fix this issue .

**Comment by jvondermarck** [comment]
Hi @Thompson6626, that's awesome, you can work on it ! 😃
