### ISSUE TITLE
Set up JUnit Test

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#11]
Create JUnit Test for each class or a specific class/method of the game to check if everything is working. This would be great to create a folder named ***test***.
Use **JUnit 5.**

**Comment by FranciscoBastos** [comment]
Hi,

My colleague Ana Rita and I are students at masters in software engineering at FEUP (https://paginas.fe.up.pt/~estudar/mesw/). As part of the evaluation of one of the curriculum units, we need to choose an open-source project and fix an issue. We would like to know if we could help with this issue?

**Comment by jvondermarck** [comment]
@FranciscoBastos Hii, we're also a team of students who are evaluated to work on an Open-Source project, so I understand you. 👍 So of course you can work on this issue and the others if you want. 💯 

I can assign this issue to you, but i can't for you friend Ana (she needs to comment this issue)

**Comment by FranciscoBastos** [comment]
Hi @jvondermarck, I'm sorry for the wait; my professor said that he would like us to choose another issue to work on. However, I can work on this issue on my own if you still let me...

**Comment by jvondermarck** [comment]
Hi, @FranciscoBastos , no worries ! If you're still up to do this issue, I'll let you assigned to it :) Thanks for letting me know.

**Comment by jvondermarck** [comment]
@FranciscoBastos Hi, are you still working on it ?

**Comment by FranciscoBastos** [comment]
Hi, @jvondermarck. Sorry, I'm not working on it.

**Comment by pgk1216** [comment]
Hello! I could take on this issue!

**Comment by jvondermarck** [comment]
@pgk1216 Hii,I'd really appreciate, thank you so much for your interest. I'll assign you this issue! 😉
