### ISSUE TITLE
[Feature]: improve design of the volume in the home screen

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#110]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

The design of the slide bar is not really great and also the icon to mute the sound.

![image](https://github.com/user-attachments/assets/f580ed03-2fc8-4e45-9db8-1775c6434d73)

### 😍 Describe the solution you'd like

- Improve the design of the slide bar
- When user clicks on mute the sound we should display a specific icon that shows the user that the music is muted and when we unmute, we should display another icon

### 👍️ Describe alternatives you've considered

- We could also handle the volume while playing, so increase / decrease the volume in the settings during a game
- Make a special button in the meny that display a kind of menu / popup to show the slide bar of the sound for example

### ✍ Additional context

Feel free to do whatever you want. You could submit a mockup of what you want to do, like a Figma or a drawing of your idea so that we can talk about it together.

**Comment by CGaneshKumar2002** [comment]
Hi @jvondermarck,, I wish to work on this. Can you assign it to me?

**Comment by jvondermarck** [comment]
Heyyy @CGaneshKumar2002 yes you can work on it ! :)

**Comment by CGaneshKumar2002** [comment]
Hey @jvondermarck, I'm a newbie to open source contribution. I've recently registered in Hacktoberfest'24. I'd really appreciate if  you add a label for this issue "hacktoberfest-accepted, so that it can count for my participation. Thanks in advance!

**Comment by jvondermarck** [comment]
No problem, I added this label ! :)

**Comment by CGaneshKumar2002** [comment]
Hi @jvondermarck, I've raised a PR for this issue. Kindly check and merge if you're okay with that. Thanks!

Screenshot for reference
![image](https://github.com/user-attachments/assets/e091093b-dc0c-42a8-b886-81cfb0ab1696)

**Comment by CGaneshKumar2002** [comment]
Hey @jvondermarck
I'll be glad if you add the label "hacktoberfest-accepted" to my PR/MR too!

PR Link:
https://github.com/dylan-power/dinosaur-exploder/pull/113
