### ISSUE TITLE
[Feature]: add bomb

### ISSUE THREAD

**Issue by ZJF39** [jvondermarck/dinosaur-exploder#121]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

Adding bombs or missiles to clear the screen is a common feature  in shooting games. Our dinosaur lacks cool screen-clearing skills.

### 😍 Describe the solution you'd like

The player will have three bombs at the beginning. By pressing B, he can launch a fan-shaped barrage to kill a large number of enemies.

### 👍️ Describe alternatives you've considered

I am a github beginner and am learning how to contribute to open source projects. At present, I have written the basic logic of the bomb function, including barrage, remaining bomb count and other functions. The demonstration video is attached below.
I'm willing to address this issue if you think it's ok. I would be grateful if you assigned this to me! Thanks in advance.

https://github.com/user-attachments/assets/23f9c049-8770-4c49-96b0-7780092a2da0

### ✍ Additional context

In subsequent updates, making props drop to replenish the number of bombs is an option that can be considered.

**Comment by ZJF39** [comment]
I've raised a PR for this issue. Please let me know if there are any feedback, thanks in advance!

**Comment by jvondermarck** [comment]
Thank you so much !! I reviewed it :)
