### ISSUE TITLE
README shields

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#15]
**Describe the solution you'd like**
I'd like to put some shields on the top of the README FILE such as a Licence, amount of Forks/contributors, how many people connected to the Dinosaur server, and so on.

**Additional context**
You can create the shield on the following website : https://shields.io/
It can be great to add the same style for each shields such as "for-the-badge".

**Comment by jdcreedon** [comment]
@jvondermarck I'll take this one, can you assign it to me please?

**Comment by jvondermarck** [comment]
Please also add : [![GitHub Actions Maven Build - Dinosaur Exploder](https://github.com/dylan-power/dinosaur-exploder/actions/workflows/maven-build.yml/badge.svg)](https://github.com/dylan-power/dinosaur-exploder/actions/workflows/maven-build.yml)
