### ISSUE TITLE
Life system

### ISSUE THREAD

**Issue by NoahAldahan** [jvondermarck/dinosaur-exploder#19]
The player needs to know when he has gotten hit, and the game has to have a way to trigger a game over.
A life system could be a great way to deal with those problems. This would be a pretty big feature since it would need UI elements to function.
The player could have 3 lives and die (trigger a game over) when his life total is depleted. His lives would be spent by getting shot by the dinosaurs.
There could also be an animation for when he gets hit (a simple flashing of the player's spaceship would be enough).

**Comment by pgk1216** [comment]
Hello~ I could handle this issue!

**Comment by jvondermarck** [comment]
@pgk1216 Hi, no problem, I assign this issue to you. Thank you so much!

**Comment by jvondermarck** [comment]
Video to help you with an example of life system : https://www.youtube.com/watch?v=y-AfsnIyIww

**Comment by SirShamrock** [comment]
Not sure if there's been much progress made on this by pgk yet, but I could also handle this issue if there isn't :)

**Comment by jvondermarck** [comment]
Hi @SirShamrock alright, I'm going to see with @pgk1216, if he didn't implement it yet, you can work on this issue! :)
