### ISSUE TITLE
Random spawning for dinosaurs

### ISSUE THREAD

**Issue by NoahAldahan** [jvondermarck/dinosaur-exploder#20]
Right now there is only one green dinosaur that spawns in the same place every time.
For a true shoot'em up experience, we could spawn dinosaurs at random places on the X axis and at random time intervals on the top of the screen.

**Comment by AlmasB** [comment]
https://github.com/AlmasB/FXGLGames/blob/d00f131f6911e5e865d540886bfab138167ca004/KeyRain/src/main/java/keyrain/KeyRainApp.java#L85-L87

is probably useful.

This looks like a fun student project, looking forward to new versions!

**Comment by jvondermarck** [comment]
@AlmasB Thank you so much for sharing us the link!
Yes definitely, it's a cool student project 👌
