### ISSUE TITLE
Scoring system

### ISSUE THREAD

**Issue by NoahAldahan** [jvondermarck/dinosaur-exploder#21]
A score that gets incremented each time the player shoots a dinosaur would make a great addition to the project !
Each time a player shoots a dinosaur, we could imagine he gets 100 more points, and the score could be shown to the player somewhere on the screen.
This is mainly a UI element.

**Comment by IanWorley** [comment]
I would like to take a shot at this issue.

**Comment by jvondermarck** [comment]
> I would like to take a shot at this issue.

Hi, thank you so much! If you have any questions you can join our discord or contact us on Gmail/ Twitter! :)
