### ISSUE TITLE
Add a .gitignore  to the repo

### ISSUE THREAD

**Issue by IanWorley** [jvondermarck/dinosaur-exploder#23]
**Is your feature request related to a problem? Please describe.**
Add a [ .gitignore ](https://www.atlassian.com/git/tutorials/saving-changes/gitignore) file to reduce the folder size of the repo

**Describe the solution you'd like**
Remove the following folders to the repo

- [target] ( https://github.com/dylan-power/dinosaur-exploder/tree/main/target/classes)
- [system] (https://github.com/dylan-power/dinosaur-exploder/tree/main/system)
- [.idea] (https://github.com/dylan-power/dinosaur-exploder/tree/main/.idea)
- [Logs] (https://github.com/dylan-power/dinosaur-exploder/tree/main/logs)
- [dinosaur-exploder.iml] (https://github.com/dylan-power/dinosaur-exploder/blob/main/dinosaur-exploder.iml)

Then add a .gitignore so these files are not pushed into the main branch.

**Comment by IanWorley** [comment]
Make this a Good First Issue

**Comment by IanWorley** [comment]
If someone does not take this issue in two weeks from the post date, I will implement this feature.

**Comment by jvondermarck** [comment]
> If someone does not take this issue in two weeks from the post date, I will implement this feature.

Hi you already can work on it, if so, keep me updated I will assign this issue to you :) @IanWorley
