### ISSUE TITLE
[Feature]: Stylized the score text label

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#24]
I'd be great to put some style on the text of the score, maybe import a special font to the game.
Add a small image next to the score maybe.
And put the text at the top-left.

**Comment by Sidahmed-ben** [comment]
hello @jvondermarck , this issue interrests me , can you assign it to me please. Thank you

**Comment by jvondermarck** [comment]
Hi @Sidahmed-ben, of course ! Thank you 👍🏻

**Comment by jvondermarck** [comment]
@Sidahmed-ben Hi are you still working on it ? Need any help ?? Let me know please.

**Comment by Sidahmed-ben** [comment]
> @Sidahmed-ben Hi are you still working on it ? Need any help ?? Let me know please.
Hello @jvondermarck , sorry I stopped working for the project because i haven't enough time.

**Comment by brianreville** [comment]
Hi @jvondermarck can you assign this to me

**Comment by jvondermarck** [comment]
Hi @brianreville i assign this issue to you! Thank you! ☺️

**Comment by shivam98** [comment]
Hi, I am new to github, want to contribute, Could you please assign this. Thanks

**Comment by jvondermarck** [comment]
Hii yeah of course @shivam98 , go ahead :)
