### ISSUE TITLE
[Feature]: Add a image icon of the game

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#25]
I'd be great to add an icon image of the game : 
![image](https://user-images.githubusercontent.com/62793491/159678890-9b16f4f0-1c50-4849-bec0-d5df083a0def.png)

Add this image from this website : https://pixabay.com/ro/illustrations/dinozaur-animal-autocolant-reptila-6072475/
You'll have to resize it and maybe convert the picture format to ico.

**Comment by SirShamrock** [comment]
Hey, I'd like to give this a shot today

**Comment by jvondermarck** [comment]
Hi @SirShamrock no problem I assign you this issue! 😉
