### ISSUE TITLE
Infinite Background and rightly fitted background image 

### ISSUE THREAD

**Issue by NoahAldahan** [jvondermarck/dinosaur-exploder#3]
An infinitely scrolling background with the current background image

**Comment by jvondermarck** [comment]
Hi Maxime, have you already choose the background image ?
I'll try to think about that issue later.

**Comment by NoahAldahan** [comment]
Hey Julien,
Yeah, I used [that one](https://github.com/dylan-power/dinosaur-exploder/blob/main/src/main/resources/assets/textures/background.png), but right now it's too large and it doesn't properly fit the app

**Comment by jvondermarck** [comment]
> Hey Julien, Yeah, I used [that one](https://github.com/dylan-power/dinosaur-exploder/blob/main/src/main/resources/assets/textures/background.png), but right now it's too large and it doesn't properly fit the app

Thank you Max.

**Comment by jvondermarck** [comment]
Hi,
I just check out the FXGL repository on GitHub and I've found this issue : 
https://github.com/AlmasB/FXGL/issues/342#issuecomment-1063157477

I hope it can help us !

**Comment by jvondermarck** [comment]
Look at : 7df6f4a4f3bf5e44bd2fcf44136564bfdfa5ac6f
Gonna do some test and make it approve by @DatBoiSaix.
