### ISSUE TITLE
[Feature]: Change format Pull Request template to YAML

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#30]
It would be great to change the Pull Request template from markdown to YAML format. 
For a quick example you can look at our issue template which look like this : [click here.](https://github.com/jvondermarck/dinosaur-exploder/blob/main/.github/ISSUE_TEMPLATE/bug_report.yaml)

**Comment by jdcreedon** [comment]
@jvondermarck can you assign this issue to me please?

**Comment by jvondermarck** [comment]
@filegrunt Hi, done. Thank you!

**Comment by jvondermarck** [comment]
Oops, so far it's not possible to change the PR template into YAML format, so unfortunately I close this issue. 😧
