### ISSUE TITLE
[Feature]: Create Java Doc

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#32]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 😍 Describe the solution you'd like

It would be great for each class of the project, to generate a Java Doc + on your own write some comments. 
It is possible to generate it on Eclipse or IntelliJ IDEA. 

### ✍ Additional context

We will be able to upload the online documentation of the whole project online by just generating the Java Doc.

**Comment by Vishrut19** [comment]
@jvondermarck Hey can I help you with this ? Or I can take up this task if you help me what to do and somethings about it

**Comment by jvondermarck** [comment]
hi @Vishrut19 yeah you can work on this issue, you just have to in each class of the repo, write comments for each methods, what the method is doing and so on. Feel free to do whatever you want, I'll review it and tell you. 
I've found this article that can help u : https://www.jetbrains.com/help/idea/working-with-code-documentation.html

**Comment by Vishrut19** [comment]
> hi @Vishrut19 yeah you can work on this issue, you just have to in each class of the repo, write comments for each methods, what the method is doing and so on. Feel free to do whatever you want, I'll review it and tell you. I've found this article that can help u : https://www.jetbrains.com/help/idea/working-with-code-documentation.html

I will try to do it and send you back for review.

**Comment by akshaywakhare** [comment]
@Vishrut19 please let me know if I can contribute along in any way

**Comment by Vishrut19** [comment]
Yes @akshaywakhare we can contribute together. What say ?

**Comment by Vishrut19** [comment]
> @Vishrut19 please let me know if I can contribute along in any way
@akshaywakhare Join the official Discord server of the project and then we can work on it.

**Comment by akshaywakhare** [comment]
> Yes @akshaywakhare we can contribute together. What say ?

yeah definitely! Lets connect over discord

**Comment by Vishrut19** [comment]
@akshaywakhare okay connect on the project's official discord server.

**Comment by Vishrut19** [comment]
Hello @jvondermarck ! Just had some queries. Can you please connect to the discord voice channel?

**Comment by jvondermarck** [comment]
Hi, sorry I'm at work right now, I can't :( but if you can write your queries, go ahead :)

**Comment by Vishrut19** [comment]
@jvondermarck Okay Actually opened and installed the whole project on my system. On VSCode it is running well but on Intellij Idea I am not able to edit or even run the project.
Can you please help me with project setup on Intellij Idea.

**Comment by jvondermarck** [comment]
Can u please show me a screenshot when you are on Intellji ? @Vishrut19 
When u download the project and unzip it, it should download automatically the dependencies otherwise run a maven command
![image](https://user-images.githubusercontent.com/62793491/189129764-03f1bb44-3c57-4866-b34b-2c19af655506.png)
![image](https://user-images.githubusercontent.com/62793491/189129980-e219d7a9-5c81-49c6-96ca-d229de02c288.png)

**Comment by Vishrut19** [comment]
@jvondermarck okay its working now let me try to do the docs part and if there is any issue then I will get back to you. Please help me because this is my first open source project.

**Comment by jvondermarck** [comment]
Awesome !! Good luck, take your time, and do not hesitate to ask questions :) @Vishrut19

**Comment by Vishrut19** [comment]
Sure and thanks @jvondermarck

**Comment by Vishrut19** [comment]
@jvondermarck This app doesn't work on MacOS ?

**Comment by jvondermarck** [comment]
Hi @Vishrut19, that's a good question... Hum nobody never tested on a Mac, but it should work if you have installed Java 17. What's the issue ?

**Comment by Vishrut19** [comment]
@jvondermarck Sorry for the late reply! The issue is that there is no command to run the app on MacOSX

**Comment by jvondermarck** [comment]
@Vishrut19 but can you run the project ? or u mean that u can't run the jar file ? give me some details

**Comment by Vishrut19** [comment]
@jvondermarck I have downloaded the zip file --> extracted it --> open the folder on IntelliJ --> then when I am trying to run normally it is not happening. Then I tried the .jar file command then also it is saying zsh: command not found

**Comment by jvondermarck** [comment]
Alright, I understand now, and do you get any errors while trying to run it ? @Vishrut19

**Comment by Vishrut19** [comment]
No I didn't get any errors while running but it is not running at all

**Comment by jvondermarck** [comment]
Huum maybe it didn't import the project correctly.
Try to do this : 
![image](https://user-images.githubusercontent.com/62793491/191559602-253fdd5a-a2aa-4ff6-8d43-595baf6d5064.png)
- then select the whole folder 
- and select import module from MAVEN

otherwise just send me a screenshot of your IDE just to see if i can see something

**Comment by Vishrut19** [comment]
@jvondermarck This is what I can see on my screen
<img width="1470" alt="Screenshot 2022-09-21 at 10 02 34 PM" src="https://user-images.githubusercontent.com/53470896/191561474-272a3f86-e218-4925-8cd7-1206333e10c4.png">

**Comment by jvondermarck** [comment]
Can u click here ? 
![image](https://user-images.githubusercontent.com/62793491/191561886-6d819f1b-b1bc-4026-9581-4c293c86964d.png)

**Comment by Vishrut19** [comment]
@jvondermarck Yes it is working

**Comment by annavordou** [comment]
Hi everyone! Do you need more help on this issue?

**Comment by Vishrut19** [comment]
Yes @annavordou you are welcome to help!

**Comment by a1j2d** [comment]
hi @jvondermarck ..! do you need any help

**Comment by jvondermarck** [comment]
hey @mjsgitt you can work on it if you want, do not hesitate :)

**Comment by a1j2d** [comment]
@jvondermarck, Is this how the **comment description** and the **flow of the comment** should be?

![GithubDino](https://user-images.githubusercontent.com/75468288/197683071-c325f458-b43e-411a-9f63-5328b2dcb63a.png)

**Comment by jvondermarck** [comment]
https://www.jetbrains.com/help/idea/working-with-code-documentation.html#auto-comment
To create a comment write : /** and pres enter to generate the comment

**Comment by a1j2d** [comment]
hey @jvondermarck, is **comment description** required for enums, and interfaces?

**Comment by jvondermarck** [comment]
Hi, @mjsgitt yeah it is recommended for an interface to comment each method, but for enums you can just explain what is the enum for :)

**Comment by a1j2d** [comment]
hey @jvondermarck, I have pushed the code with comments in CommentsbyMj branch , review it or suggest any changes to do.

**Comment by a1j2d** [comment]
@jvondermarck  did you receive the update which I pushed ??

**Comment by paragpatil01** [comment]
Hello everyone, I'm new in tech actually I'm come from non tech background but now i have to switch into tech. I'm learning java right now. Anyone can help me guide me how to connect in open source project and how I contribute

**Comment by jvondermarck** [comment]
Hi, welcome to the Open Source world ! First, I would advice to read our Contributing file : https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md
Do not hesitate to help on creating some issues to improve the game or to work on some opened issues ! @paragpatil01

**Comment by paragpatil01** [comment]
Hi @jvondermarck , thank you for giving mw the chance ! as per your advice  I read all contributing file and understand. now tell me that how can i contribute in this project. I'm a beginner so guide me how to do open source contribution. I just completed java

**Comment by paragpatil01** [comment]
@jvondermarck Actually some day ago I don't have understanding about git and github  but I take some time and learn git and github and coming back to you for contribution guide me how to do open source project

**Comment by jvondermarck** [comment]
@paragpatil01 Hi ! Great I'm glad that you are motivated to contribute !
I advice you to go to this website : https://opensource.guide/how-to-contribute/
And then, take an issue that can interests you and work on it ! Or try the game, if you see anything that can be improve, just create some issues on our repository to add features / fix a bug and work on it or let some people adding these features.

**Comment by paragpatil01** [comment]
@jvondermarck Hi ! I play this game. such a amazing game ! but I think we should improve one thing, when  I start this game I'm able to play well  I kill dinosaur  and improving my score but  the bullets come from dinosaur side that injured me rapidly and decrease my health and I get Gameover too fast. so the idea is to add a function improve health. like when player scored 20 or 25 he get reward and the reward is to increase health one time. so with this function player can continue the game and scored more  (please note : My English is little bit improper but the idea about reward is great so please think abut it) and if you like this suggestion then give me a chance to work on this because I'm glad to work on this project and Implement my idea on realworld is great thing for me.

**Comment by jvondermarck** [comment]
@paragpatil01 Hi, that is an awesome idea ! I suggest you to create a feature issue on the repo and work on it ! And submit a Pull Request after :)

**Comment by igmtz** [comment]
Hello @jvondermarck ! I'm new on the open source world, so I would like to contribute on this issue. I don't have pretty much clear if someone is currently working on writing documentation, but I can contribute with that. Also, I noticed that there is some testing documents created but with no tests implemented, so I can add some. Let me know if I can help!

**Comment by jvondermarck** [comment]
Hi @igmtz welcome to the open source world !! Feel free to work on any opened issue on the repository, so far the project has been a bit inactive so I guess that nobody is currently working on a specific issue. So yeah I can advice you to work on what you like the most ! :)
You can also create some new issue on the repo for bug/new feature to improve the project ! 
Thanks

**Comment by jvondermarck** [comment]
@igmtz Could you just tell me how did you find this repository please ? I'm interested how people can discover us :)

**Comment by igmtz** [comment]
@jvondermarck sure! I was looking up for some issues to contribute and I found some "Good First Issue" websites and that's how I found your project 😄

**Comment by axelthepony27** [comment]
Hello everyone. I'm new to the open source community, and found this project on a list for begginer-friendly repos. Can I contribute to this issue?

**Comment by jvondermarck** [comment]
Hi @axelthepony27 of course you can contribute to this open source project ! 😃

**Comment by axelthepony27** [comment]
> Hi @axelthepony27 of course you can contribute to this open source project ! 😃

@jvondermarck Thank you very much :)
Are there any guidelines or style preferences I should adhere to?
