### ISSUE TITLE
[Feature]: README How to play add info

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#33]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 😍 Describe the solution you'd like

It would be great on the README file, at the ["How to play" section](https://github.com/dylan-power/dinosaur-exploder#-how-to-play), to add the different keys to play on the game. 

### ✍ Additional context
quick example on how it can look like : 
<kbd>SPACE </kbd> : throw projectile,
and so on...

**Comment by Tomiiwa** [comment]
Hi, I'd like to work on this

**Comment by jvondermarck** [comment]
@Tomiiwa Hi, great! I assigned you this issue :) Enjoy. 👍

**Comment by Tomiiwa** [comment]
The link to download the game is leading back to github. How do I check for the required controls?

**Comment by jvondermarck** [comment]
@Tomiiwa Yea I'm sorry, it's normal because we didn't create the executable yet, so you'll have to install the project locally (be aware to download Java FX first on your machine) and then you'll be able to run the game on Eclipse/Intellij.

**Comment by jvondermarck** [comment]
@Tomiiwa You can check out the code here to know the different keys to play the game : https://github.com/dylan-power/dinosaur-exploder/blob/main/src/main/java/com/dinosaur/dinosaurexploder/controller/DinosaurController.java

**Comment by Tomiiwa** [comment]
Got it, thanks
