### ISSUE TITLE
[Feature]: Create a home screen on startup

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#39]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 😍 Describe the solution you'd like

It can be great to have a home screen when we start the game to avoid playing the game directly when you start. We would have to press enter to start gaming.

### 👍️ Describe alternatives you've considered

You can use this [background ](https://github.com/dylan-power/dinosaur-exploder/blob/main/src/main/resources/assets/textures/background.png).

Please try to find a good font to write the text. 
Please be aware to create a pretty home screen with the good [dimension of the application (check line 7 and 8](https://github.com/dylan-power/dinosaur-exploder/blob/main/src/main/java/com/dinosaur/dinosaurexploder/view/DinosaurGUI.java) : 

![image](https://user-images.githubusercontent.com/62793491/160784799-11e747aa-8005-4c4b-8781-7a8e67897d42.png)
(This image is just a prototype)

### ✍ Additional context
You can send us a picture before doing a pull request, just so we can all agree on the design. (Contact us on Discord, GitHub discussions, Twitter, Gmail)

**Comment by jvondermarck** [comment]
I found on the FXGL documentation a section on how to [create a menu](https://github.com/AlmasB/FXGL/wiki/Customizing-Menus-%28FXGL-11%29 ), maybe it can help you :) 
This [video ](https://www.youtube.com/watch?v=SPJQmWVVX-U) and/or [this one too](https://www.youtube.com/watch?v=iWhtz5EUJFk) can help you also.
I found a repository with a Home Screen menu [click here (start line 32)](https://github.com/leewyatt/FXGL_Tank/blob/main/src/main/java/com/itcodebox/tank/ui/GameMenu.java).

**Comment by pgk1216** [comment]
Hello! I could work on this issue!

**Comment by jvondermarck** [comment]
@pgk1216 Hi,of course you can work on it. I'll assign you this issue. Thank you so much 👌
