### ISSUE TITLE
[Feature]: Animation when the dinosaurs get killed

### ISSUE THREAD

**Issue by NoahAldahan** [jvondermarck/dinosaur-exploder#47]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

The game is called dinosaur exploder, but when you shoot on the dinosaurs, they only disappear, they don't explode

### 😍 Describe the solution you'd like

An animation using the FXGL framework of an explosion when the dinosaurs are killed

It can look like this : 
- https://github.com/AlmasB/FXGLGames/blob/master/SpaceInvaders/src/main/resources/assets/textures/explosion.png
![image](https://user-images.githubusercontent.com/62793491/167271306-cb07fbd4-eb38-44a8-b0d6-235f1b2a3d9d.png)

### 👍️ Describe alternatives you've considered

No alternatives to total destruction I'm afraid

**Comment by jvondermarck** [comment]
Great video that shows an explosion : https://www.youtube.com/watch?v=80xmzyp-IMc

**Comment by SirShamrock** [comment]
Hi, I'd like to give this a go, and see if I can achieve it for you guys

**Comment by jvondermarck** [comment]
Hi @SirShamrock ,no problem go ahead I assign this issue to you. Good luck!
It looks a bit complicated to work on this issue to make a good visual rendering, so if you need any help or need advice just contact us on our discord server if u want! :)

**Comment by QwitherY** [comment]
Hi, I'm willing to work on this issue, and I have created a pull request for it:'#117'
