### ISSUE TITLE
[Feature]: Sideway movement animation

### ISSUE THREAD

**Issue by NoahAldahan** [jvondermarck/dinosaur-exploder#5]
An animation for when the spaceship is moving sideways, right now it feels a bit boring

**Comment by jvondermarck** [comment]
An example : 
![image](https://user-images.githubusercontent.com/62793491/167271171-d3c4767a-8575-4514-aa78-acde6d3dd7f8.png)

**Comment by gabrielaramburu** [comment]
Hi,
I think, I have implemented this movement animation.

![imagen](https://user-images.githubusercontent.com/63823685/178379697-55f32384-6d97-47c7-8a22-15d8c33427fe.png)
 I can make a PR if you want.

best regards
Gabriel

**Comment by nilanjanH** [comment]
@NoahAldahan - Is this issue resolved now?
Thanks.

**Comment by jvondermarck** [comment]
Hi @nilanjanH, I forgot to close the issue, but you still can improve the sideway animation, feel free to contribute to make it better and better ! If you have any ideas on how to improve it, work on the issue, otherwise I will close this issue if you don't want to work ont it.

**Comment by nilanjanH** [comment]
@jvondermarck Thanks for replying. You can  close this now, I'll create an enhancement issue if I find the scope for it.
🙂

**Comment by jvondermarck** [comment]
Alright @nilanjanH , don't hesitate to create issue if u find something to improve the project :)
