### ISSUE TITLE
[Bug-Feature]: Options Menu not working as intended

### ISSUE THREAD

**Issue by SirShamrock** [jvondermarck/dinosaur-exploder#56]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate bugs.

### ❌ Current Behavior

The options menu within the pause menu that can be accessed within the game by pressing 'Esc' has some issues.

1. 'Gameplay' button has no visible function when clicked
2. 'Controls' shows action0, action1, etc.
3. 'Video' shows language options
4. All tabs' text is merging with the original options menu text

### ✅ Expected Behavior

1. 'Gameplay' should have a function
2. 'Controls' should show 'Move Up', 'Move Down', etc.
3. 'Video' tab would perhaps be better renamed 'Language'
4. All tabs text should be easy to read without other options text getting in way

### 🚩 Steps To Reproduce

The image below is an example showing problems 2 and 4.

![image](https://user-images.githubusercontent.com/100976263/167256752-aef86cf1-91ec-43b0-8f52-9548df4d8bcf.png)

### 💻 Environment

```markdown
- OS: Windows 10
- Game version: 1.0.0
```

**Comment by jvondermarck** [comment]
Hi thank you for this issue. This menu is implemented by the FXGL framework so it's normal, I'd turn this issue to a feature issue.
For people who will work on it you can find some tutorials to change the menu : 
+ Youtube video : https://www.youtube.com/watch?v=iWhtz5EUJFk
+ https://github.com/AlmasB/FXGL/discussions/1103 
+ Documentation : https://github.com/AlmasB/FXGL/wiki/Customizing-Menus-%28FXGL-11%29

**Comment by nadia12-p** [comment]
Hi! Can I work on this?

**Comment by jvondermarck** [comment]
Hi @nadia12-p yeah go ahead :)

**Comment by nadia12-p** [comment]
Hi @jvondermarck I have a couple of questions on the layout of the pause menu.

1. Do you want all the default buttons to stay on the layout? I think the Video and Restore buttons aren't really relevant to our game right now but I can leave them and we can add a functionality to them later, what do you think?
2. What is the difference between the Gameplay and Controls buttons? 
3. The title's style is overridden when I customize the menu, do you want the style to remain the same as the default pause menu or do you want it to be like the main Menu title style?
4. The v1.0-Developer text at the bottom left is also overridden, do you want me to add it back? 

if you have another idea of the style, please let me know so I can modify the layout :D

**Comment by jvondermarck** [comment]
Hi @nadia12-p 

1. Indeed, the Video and Restore buttons aren't really relevant to our game.
2. I have no idea what is the difference between Gameplay and Controls buttons, but I'd say maybe to remove the Gameplay button and edit the Controls button to have all the controls of the game (u can see all the controls right [here.](https://github.com/dylan-power/dinosaur-exploder#-how-to-play)
3. Huum I think you can choose by yourself the most aesthetic and beneficial display possible, you have every right to choose between the two possibilities :)
4. Yeahh absolutely you can add it back if you want.

For the moment everything is good for me, submit your PR when you'll have finish everything and I'll review it. Thank you so much for you contribution.
