### ISSUE TITLE
[Feature]: Create a design when player die

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#58]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

When the player lives come to 0, we die, and it exit the game, so right now it's a bit frustrating to re-start the game to play again.

### 😍 Describe the solution you'd like

When we die, it would be great to display a message to the user.  
It can look like this : 
![image](https://user-images.githubusercontent.com/62793491/167270899-545b287d-c59f-495d-a34e-c2ab5a0e00ba.png)

Or maybe looks like this (much better) : 
![image](https://user-images.githubusercontent.com/62793491/167270978-f64a96b1-2408-415a-bb3f-59052e8bcd28.png)

### 👍️ Describe alternatives you've considered

A good design would be really appreciated to have a good user experience with the game.

**Comment by andresmc98** [comment]
Hi, is someone working on this issue? 
i'd like to take it

**Comment by jvondermarck** [comment]
Hi @andresmc98 yeah definitely! Thank you.

**Comment by andresmc98** [comment]
Thanks c: @jvondermarck , 
I already can run the project so if i have a doubt or a progress i tell you c:
also im on your disc serv

**Comment by jvondermarck** [comment]
That's great if you can run it! No worries, don't hesitate to ask any questions you want. To help you, I advice you to look at some FXGL projects on GitHub or YouTube, you can find examples there to solve this issue! 🙂

**Comment by andresmc98** [comment]
Hello i made a version 1.0 of the game over screen like this
<img width="553" alt="Screen Shot 2022-07-03 at 14 35 59" src="https://user-images.githubusercontent.com/52982047/177069287-b0d259be-f6b4-4bb9-88f0-ba4401dd3eaa.png">

soon i'll try to made the other kind of screen c:

**Comment by jvondermarck** [comment]
Great well done !!
