### ISSUE TITLE
[Feature]: Put a red background when spaceship get hit

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#59]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 😍 Describe the solution you'd like

When we get hit by a dinosaur, it would be better to put a red background to make the user realize that he got hit.
![image](https://user-images.githubusercontent.com/62793491/167271386-08854472-185f-4a72-b71e-e6a97af48788.png)

### 👍️ Describe alternatives you've considered

Example of a code to put a little flash when we get hit : 
https://github.com/AlmasB/FXGLGames/blob/master/SpaceInvaders/src/main/java/com/almasb/fxglgames/spaceinvaders/SpaceInvadersController.java#L132

**Comment by nadia12-p** [comment]
Hey, I was looking at the project and I'm interested to keep contributing, can I take this issue?

**Comment by jvondermarck** [comment]
Yeah @nadia12-p, go ahead! Thank you so much! 🙂
