### ISSUE TITLE
Avoid leaving the game screen

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#6]
**Describe the bug**
We can go outside the game screen. 

**To Reproduce**
1. When we click on the left or right keyboard multiple times. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.0

**Comment by pgk1216** [comment]
Hello~ I could take care of this problem!

**Comment by jvondermarck** [comment]
@pgk1216 Hii, alright no problem I assign this issue to you! Thank you so much for your interest contributing to our project!!
