### ISSUE TITLE
[Feature]: Update the life system design

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#60]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 😍 Describe the solution you'd like

So far, the display of the number of lives remaining looks like this:
![image](https://user-images.githubusercontent.com/62793491/167271554-fb879d33-afcd-45b3-8308-e6790e532766.png)

it might be better to have hearts instead : 
![image](https://user-images.githubusercontent.com/62793491/167271578-674ddb05-f474-4f44-bc75-9fce592aef40.png)

Example of the above asset : 
https://github.com/AlmasB/FXGLGames/blob/master/SpaceInvaders/src/main/resources/assets/textures/life.png

**Comment by ValerieRossDEV** [comment]
Hi, I'd like to give this issue a go. Is it still open?

**Comment by jvondermarck** [comment]
Hi @ValerieRossDEV yep of course, go ahead 🙂

**Comment by andresmc98** [comment]
Hi, still need help on this issue?

**Comment by jvondermarck** [comment]
Hi @andresmc98 yeah the issue is still open, you can work on it :) Thanks

**Comment by jvondermarck** [comment]
You can help to solve this PR : https://github.com/dylan-power/dinosaur-exploder/pull/72 
There is an issue on it, so it can be cool if you can work from the work of @ValerieRossDEV.

**Comment by jvondermarck** [comment]
You can help to solve this PR : https://github.com/dylan-power/dinosaur-exploder/pull/72 @andresmc98 
There is an issue on it, so it can be cool if you can work from the work of @ValerieRossDEV.

**Comment by singhparmeetb** [comment]
Hi, uh, I actually developed the heart system in a different way and only now I realized that there's already a different code/PR for that purpose. I am new to open source and github altogether, so naturally I missed out the issues section. 
Will you like to take a look at my code? or Should I commit the changes?
Will be waiting for your feedback!

**Comment by jvondermarck** [comment]
Hi @Dedmondium thank you so much for your contribution. Open a Pull Request, and i'll check ! There is an old PR about this issue that just doesn't work so if everything is working for you, i'll approve it. Thanks 😎 Welcome to the world of contribution !
