### ISSUE TITLE
[Bug]: Grammatical error in PR template

### ISSUE THREAD

**Issue by SirShamrock** [jvondermarck/dinosaur-exploder#62]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate bugs.

### ❌ Current Behavior

![image](https://user-images.githubusercontent.com/100976263/167309491-8c14909a-f3c8-461c-a6ed-89a096d879f8.png)

### ✅ Expected Behavior

Proper grammar such as : 'Thanks for contributing to this project!'

### 🚩 Steps To Reproduce

![image](https://user-images.githubusercontent.com/100976263/167309542-93cc5e28-ebcb-4013-b864-571777eaf4a2.png)

### 💻 Environment

```markdown
- OS: Windows 10
- Game version: 1.0.0
```

**Comment by jvondermarck** [comment]
Oops, thanks ! 😅
