### ISSUE TITLE
[Fix]: correct typo issues in README and PR template

### ISSUE THREAD

**Issue by Gilithrimm** [jvondermarck/dinosaur-exploder#90]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate bugs.

### ❌ Current Behavior

![IMG_20230704_210651](https://github.com/dylan-power/dinosaur-exploder/assets/88885129/bf670993-0bea-4e75-b0cc-c6eb42ff9dd1)

### ✅ Expected Behavior

⬅️`Left Arrow`: move spaceship left.

### 🚩 Steps To Reproduce

![IMG_20230704_210651](https://github.com/dylan-power/dinosaur-exploder/assets/88885129/7f55eb15-4ce6-439a-986b-7a6e353e7e7c)

### 💻 Environment

```markdown
- OS: Android 9 MIUI Global 11.0.8
- Game version: 1.0.0
```

### ℹ️ Additional information

Also:
1. Up arrow emoji is rendered differently (for some reason) 
2. #62 isn't fixed

**Comment by jvondermarck** [comment]
Great ! Would you want to work on this issue ?

**Comment by Gilithrimm** [comment]
Yeah, sure, I'll try
