### ISSUE TITLE
[Feature]: align game info text

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#93]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

The lives and score text is not aligned on the same vertical axis.
![image](https://github.com/dylan-power/dinosaur-exploder/assets/62793491/b2626f8e-7364-4494-99fa-be9ad7ded168)

### 😍 Describe the solution you'd like

It should be aligned.

**Comment by diegoborbadev** [comment]
Is the issue still open? Can I solve it?

**Comment by diegoborbadev** [comment]
@jvondermarck Assign this to me please

**Comment by jvondermarck** [comment]
heyyy @diegoborbadev, you can work on this issue! thank you !! ☺️

**Comment by diegoborbadev** [comment]
@jvondermarck Should life be on the left side under the score?

**Comment by jvondermarck** [comment]
hi @diegoborbadev yeah why not to have it on the left side :)

**Comment by diegoborbadev** [comment]
Sorry for the delay, I have been quite occupied in the past few months 😅
