### ISSUE TITLE
[Refactor]: creating a class to hold all constants

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#94]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

https://github.com/dylan-power/dinosaur-exploder/blob/13c403b6aedec5088eb5cbf18b2eda4046e01d2e/src/main/java/com/dinosaur/dinosaurexploder/controller/DinosaurController.java#L63C1-L70C41

### 😍 Describe the solution you'd like

It would be a good idea to refactor the code by creating a class to hold all constants and reusable code. This will improve code organization, readability, and maintainability. 

Change this line : 
```
public void initGame() {
      ...
      FXGL.play("gameBackground.wav");
      ...
```

To something like that :

```
public class GameConstants {
    public static final String BACKGROUND_MUSIC = "gameBackground.wav";
    // Add more constants here if needed
}

public void initGame() {
     ...
     FXGL.play(GameConstants.BACKGROUND_MUSIC);
     ...
}
```

### 👍️ Describe alternatives you've considered

You'll have to look in each classes to make this refactor.

**Comment by MelissaAyllon** [comment]
Hi, I would like to work on this.

**Comment by jvondermarck** [comment]
Hi @MelissaAyllon, great !! Good luck !
