### ISSUE TITLE
[Feature]: add "High Score" option on-game

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#95]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 😍 Describe the solution you'd like

It would be more challenging to display the highest score that the user has on all his games (and maybe even save this score somewhere so that when he restarts the game, the high score is not reset to 0).

**Comment by axelthepony27** [comment]
Hi @jvondermarck. I'd like to contribute to solve this issue. What are the requirements?

**Comment by jvondermarck** [comment]
Hi @axelthepony27, sorry for the late answer, but there are no requirements for this issue, do whatever you want, and I'll review it after :) Do you still wanna work on the issue though ?
