### ISSUE TITLE
[Feature]: add internationalization 🌍

### ISSUE THREAD

**Issue by jvondermarck** [jvondermarck/dinosaur-exploder#99]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 😍 Describe the solution you'd like

It would be a good idea to add internationalization. In the menu, the player would be able to select the game's application language. You can add English (default), French, Spanish, German, Russian, and so on... 😍

### 👍️ Describe alternatives you've considered

We now need to avoid writing the string text in plain text. We must obtain the text to be displayed by obtaining the correct text according to the language chosen by the user. 
![image](https://github.com/dylan-power/dinosaur-exploder/assets/62793491/c2cfe2c9-ae9f-4fda-820a-1bd302df3b13)

**Comment by fnwirth** [comment]
I would be happy to assist

**Comment by jvondermarck** [comment]
Hello @fnwirth, thank you so much, you can contribute to this issue !! :)

**Comment by fnwirth** [comment]
I created a first draft which so far does not make use of FXGLs own localization feature as I had some trouble using it. However, I could push my draft using an own small class for localization management as a first step once I am added as a contributor to the repository.

**Comment by jvondermarck** [comment]
Hi @fnwirth, that's really good that you created a first draft ! I can't add you as contributor to the repository, so please refer to our  [CONTRIBUTING.md](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md), you will need to fork the repository and then submit a Pull Request in this repository. Thank you so much !

**Comment by jvondermarck** [comment]
The issue is still open and needs to be done.

**Comment by RBP98** [comment]
> The issue is still open and needs to be done.

I would like to contribute to this issue

**Comment by jvondermarck** [comment]
> > The issue is still open and needs to be done.
> 
> 
> 
> I would like to contribute to this issue

Hi, awesome, you can work on it ! 😊

**Comment by itsVrushal** [comment]
Hello, could I contribute to the issue? Actually I am new to open source and I might need some assistance but I am willing to help.

**Comment by itsVrushal** [comment]
> Hello, could i contribute to the issue? Actually i am new to open source and i might need some assistance but i am willing to help.

I have made some changes can i create a pull request?
